# This workflow will build a Java project with Maven
name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types:
      - opened
      - edited
      - synchronize
      - reopened
    
  workflow_call:

jobs:

  setup:
    uses: damews/java-boot-camp-cicd/.github/workflows/setup.yml@master

  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master

  test:
    needs: setup
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: maven
      - name: Run Maven Build and tests
        run: mvn test
      
  build:
    needs: [ linter, test ]
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Run Maven Build and tests
        run: mvn install -DskipTests=true
