# This workflow will build a Java project with Maven
name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types:
      - opened
      - edited
      - synchronize
      - reopened
    
  workflow_dispatch:

jobs:

  setup:
    uses: damews/java-boot-camp-cicd/.github/workflows/setup.yml@master

  test_and_build:
    needs: setup
    name: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: maven
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: mvn -version
      - name: Run Maven Build and tests
        run: mvn package
