name: Deploy

on:
  push:
    tags: 
      - '*'

jobs:
  setup:
    name: Setup Java and Verify Dependencies
    uses: damews/java-boot-camp-cicd/.github/workflows/setup.yml@master
  build:
    name: Build and Test
    uses: damews/java-boot-camp-cicd/.github/workflows/build-and-test.yml@master
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    name: deploy
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: maven
      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp lambdas/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - uses: ncipollo/release-action@v1
        with:
          body: 'My Release'
          artifacts: "staging/**"
      
