name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  setup:
    name: Setup Java and Verify Dependencies
    uses: damews/java-boot-camp-cicd/.github/workflows/setup.yml@master
  build:
    name: Build and Test
    uses: damews/java-boot-camp-cicd/.github/workflows/build-and-test.yml@master
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: maven
      - name: Maven deploy
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging